import * as Phaser from 'phaser';
import { TILE_SIZE } from '../../config';
import type { DebugParams } from '../../debugParams';
import type { SpriteAtlasInfo } from '../../data/artManifest';
import { registerSpriteFrames } from '../spriteFrames';
import { DataKey, DEFAULT_PACK_DIR, PackFile, SceneKey, TextureKey } from './keys';

const PARTICLE_PX = 2;

/** Loads what every other scene needs, then hands over to the title (or a debug start scene). */
export class BootScene extends Phaser.Scene {
  constructor(private readonly params: DebugParams) {
    super(SceneKey.Boot);
  }

  preload(): void {
    // Generated by `npm run art:pack`; served from assets/ (Vite publicDir).
    this.load.setPath(`${this.params.pack ?? DEFAULT_PACK_DIR}/`);
    const frame = { frameWidth: TILE_SIZE, frameHeight: TILE_SIZE };
    this.load.spritesheet(TextureKey.tiles, PackFile.tiles, frame);
    this.load.spritesheet(TextureKey.walls, PackFile.walls, frame);
    this.load.spritesheet(TextureKey.cracks, PackFile.cracks, frame);
    this.load.image(TextureKey.sprites, PackFile.sprites);
    this.load.json(DataKey.sprites, PackFile.spritesInfo);
  }

  create(): void {
    registerSpriteFrames(
      this.textures.get(TextureKey.sprites),
      this.cache.json.get(DataKey.sprites) as SpriteAtlasInfo,
    );
    // Particles are tinted per burst, so a single white pixel texture serves them all.
    this.make
      .graphics({}, false)
      .fillStyle(0xffffff)
      .fillRect(0, 0, PARTICLE_PX, PARTICLE_PX)
      .generateTexture(TextureKey.particle, PARTICLE_PX, PARTICLE_PX)
      .destroy();
    const next = { title: SceneKey.Title, game: SceneKey.Game, 'art-test': SceneKey.ArtTest }[
      this.params.scene
    ];
    this.scene.start(next);
  }
}
