import * as Phaser from 'phaser';
import { TILE_SIZE } from '../../config';
import type { StartScene } from '../../debugParams';
import { AtlasUrl, SceneKey, TextureKey } from './keys';

const PARTICLE_PX = 2;

/** Loads what every other scene needs, then hands over to the title (or a debug start scene). */
export class BootScene extends Phaser.Scene {
  constructor(private readonly startScene: StartScene) {
    super(SceneKey.Boot);
  }

  preload(): void {
    // Generated by `npm run art:placeholder`; served from assets/ (Vite publicDir).
    const frame = { frameWidth: TILE_SIZE, frameHeight: TILE_SIZE };
    this.load.spritesheet(TextureKey.placeholderTiles, AtlasUrl.tiles, frame);
    this.load.spritesheet(TextureKey.placeholderWalls, AtlasUrl.walls, frame);
    this.load.spritesheet(TextureKey.cracks, AtlasUrl.cracks, frame);
  }

  create(): void {
    // Particles are tinted per burst, so a single white pixel texture serves them all.
    this.make
      .graphics({}, false)
      .fillStyle(0xffffff)
      .fillRect(0, 0, PARTICLE_PX, PARTICLE_PX)
      .generateTexture(TextureKey.particle, PARTICLE_PX, PARTICLE_PX)
      .destroy();
    this.scene.start(this.startScene === 'game' ? SceneKey.Game : SceneKey.Title);
  }
}
