import * as Phaser from 'phaser';
import { TILE_SIZE } from '../../config';
import { PALETTE } from '../../data/palette';
import type { DebugParams } from '../../debugParams';
import type { SpriteAtlasInfo } from '../../data/artManifest';
import { SPRITE_ASSETS } from '../../data/spriteAssets';
import { LIQUID_FRAME, LIQUID_FRAME_COUNT } from '../liquidFrames';
import { makeShaftTexture } from '../LightShafts';
import { registerSpriteFrames } from '../spriteFrames';
import { DataKey, DEFAULT_PACK_DIR, PackFile, SceneKey, TextureKey } from './keys';

const PARTICLE_PX = 2;
const SUN_RADIUS = 11;
const MOON_RADIUS = 8;
/** Glow sprite size; drawn smooth (linear filtering) and scaled to each light's radius. */
const GLOW_PX = 64;
/** Liquid opacity: water lets the cave behind it show through, lava barely does. */
const WATER_ALPHA = 0.55;
const LAVA_ALPHA = 0.92;
/** Height of the lighter band on a surface frame. */
const LIQUID_SURFACE_PX = 2;
const LIQUID_SURFACE_ALPHA = 0.85;

/** Loads what every other scene needs, then hands over to the title (or a debug start scene). */
export class BootScene extends Phaser.Scene {
  constructor(private readonly params: DebugParams) {
    super(SceneKey.Boot);
  }

  preload(): void {
    // Generated by `npm run art:pack`; served from assets/ (Vite publicDir).
    this.load.setPath(`${this.params.pack ?? DEFAULT_PACK_DIR}/`);
    const frame = { frameWidth: TILE_SIZE, frameHeight: TILE_SIZE };
    this.load.spritesheet(TextureKey.tiles, PackFile.tiles, frame);
    this.load.spritesheet(TextureKey.walls, PackFile.walls, frame);
    this.load.spritesheet(TextureKey.cracks, PackFile.cracks, frame);
    this.load.image(TextureKey.sprites, PackFile.sprites);
    this.load.json(DataKey.sprites, PackFile.spritesInfo);
    this.load.json(DataKey.pack, PackFile.info);
    // Standalone textures (parallax, foreground canopy): one PNG per asset, texture key = asset id.
    for (const asset of SPRITE_ASSETS) {
      if (asset.standalone) this.load.image(asset.id, `${asset.id}.png`);
    }
  }

  create(): void {
    registerSpriteFrames(
      this.textures.get(TextureKey.sprites),
      this.cache.json.get(DataKey.sprites) as SpriteAtlasInfo,
    );
    // Particles are tinted per burst, so a single white pixel texture serves them all.
    this.make
      .graphics({}, false)
      .fillStyle(0xffffff)
      .fillRect(0, 0, PARTICLE_PX, PARTICLE_PX)
      .generateTexture(TextureKey.particle, PARTICLE_PX, PARTICLE_PX)
      .destroy();
    this.makeSkyBodies();
    this.makeGlow();
    makeShaftTexture(this.textures);
    this.makeLiquids();
    const next = { title: SceneKey.Title, game: SceneKey.Game, 'art-test': SceneKey.ArtTest }[
      this.params.scene
    ];
    this.scene.start(next);
  }

  private makeSkyBodies(): void {
    const d = SUN_RADIUS * 2 + 2;
    this.make
      .graphics({}, false)
      .fillStyle(PALETTE.honey[1])
      .fillCircle(d / 2, d / 2, SUN_RADIUS)
      .fillStyle(PALETTE.gold[3])
      .fillCircle(d / 2, d / 2, SUN_RADIUS - 1)
      .fillStyle(PALETTE.honey[3])
      .fillCircle(d / 2 - 2, d / 2 - 2, SUN_RADIUS - 5)
      .generateTexture(TextureKey.sun, d, d)
      .destroy();
    const m = MOON_RADIUS * 2 + 2;
    this.make
      .graphics({}, false)
      .fillStyle(PALETTE.moonSilver[1])
      .fillCircle(m / 2, m / 2, MOON_RADIUS)
      .fillStyle(PALETTE.moonSilver[3])
      .fillCircle(m / 2, m / 2, MOON_RADIUS - 1)
      .fillStyle(PALETTE.moonSilver[2])
      .fillCircle(m / 2 + 2, m / 2 + 1, 2)
      .fillCircle(m / 2 - 3, m / 2 - 2, 1)
      .generateTexture(TextureKey.moon, m, m)
      .destroy();
  }

  /** White radial falloff (bright centre, smooth edge) used by the additive glow pass. */
  private makeGlow(): void {
    const texture = this.textures.createCanvas(TextureKey.glow, GLOW_PX, GLOW_PX);
    if (!texture) return;
    const ctx = texture.context;
    const r = GLOW_PX / 2;
    const gradient = ctx.createRadialGradient(r, r, 0, r, r, r);
    gradient.addColorStop(0, 'rgba(255,255,255,1)');
    gradient.addColorStop(0.35, 'rgba(255,255,255,0.45)');
    gradient.addColorStop(1, 'rgba(255,255,255,0)');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, GLOW_PX, GLOW_PX);
    texture.refresh();
    texture.setFilter(Phaser.Textures.FilterMode.LINEAR);
  }

  /**
   * Static liquid tiles (frame layout in liquidFrames.ts): flat translucent bodies, with a lighter
   * band on top for surface cells. Real liquid art and waves come with flowing liquids.
   */
  private makeLiquids(): void {
    const texture = this.textures.createCanvas(
      TextureKey.liquids,
      LIQUID_FRAME_COUNT * TILE_SIZE,
      TILE_SIZE,
    );
    if (!texture) return;
    const ctx = texture.context;
    const css = (rgb: number, alpha: number): string =>
      `rgba(${(rgb >> 16) & 0xff},${(rgb >> 8) & 0xff},${rgb & 0xff},${alpha})`;
    const draw = (frame: number, body: number, top: number | null, alpha: number): void => {
      const x = frame * TILE_SIZE;
      ctx.fillStyle = css(body, alpha);
      ctx.fillRect(x, 0, TILE_SIZE, TILE_SIZE);
      if (top === null) return;
      ctx.clearRect(x, 0, TILE_SIZE, LIQUID_SURFACE_PX);
      ctx.fillStyle = css(top, Math.max(alpha, LIQUID_SURFACE_ALPHA));
      ctx.fillRect(x, 0, TILE_SIZE, LIQUID_SURFACE_PX);
    };
    // Frame 0 stays transparent: the GPU layer samples it for empty cells.
    draw(LIQUID_FRAME.waterBody, PALETTE.cyan[1], null, WATER_ALPHA);
    draw(LIQUID_FRAME.waterSurface, PALETTE.cyan[1], PALETTE.cyan[3], WATER_ALPHA);
    draw(LIQUID_FRAME.lavaBody, PALETTE.ember[2], null, LAVA_ALPHA);
    draw(LIQUID_FRAME.lavaSurface, PALETTE.ember[2], PALETTE.honey[3], LAVA_ALPHA);
    texture.refresh();
  }
}
